### ISSUE TITLE
Restructure database for different types of vehicles

### ISSUE THREAD

**Issue by JakubKermes** [blumilksoftware/e-motion-api#214]

**Comment by AleksandraKozubal** [comment]
For now i found:

1.  12 websites with bikes and e-bikes
2. one with scooters
3. one with emopeds
4. one with cargo
5. one with motorscooters

I am thinking if we should add all types of micromobility that we can find, or just escooters and bikes/ebikes?

**Comment by AleksandraKozubal** [comment]
Sound's good for me.
